export const mascotPhrases = {
  idle: [
    'Bibi...',
    'Mmm hmm...',
    'Zibi zibi...',
    'Booba...',
    'Hmmmm...',
    'Tiki tiki...',
    'Mimi...',
    'Ooo...',
    'Papoi...',
    'Bello bello...',
  ],

  clicked: [
    'Papoi!',
    'Bello!',
    'Papoi papoi!',
    'Booba!',
    'Heyyy human!',
    'What?! What?!',
    'Hehehehe!',
    'Bibi bada boop!',
    'Ooooh! You click me!',
    'Me is here!',
    'Banana boom!',
    'Po-ka po-ka!',
    'Bababooey!',
    'Tadaaa!',
    'Waaazaaa!',
    'Yippee!',
    'Boing boing!',
    'Hehehe! Again again!',
    'Papoi! Study time!',
    'Bello human!',
    'Me awake!',
    'No poke me! Hehehe!',
    'Okey dokey!',
    'Waka waka!',
    'Bibi bobo!',
    'Me ready!',
    'Whoa! Big click!',
    'Aiyaaa!',
    'Papoyyy!',
    'Banana brain!',
    'Booky booky!',
    'Focus-o!',
    'Brain go brrrr!',
    'Me smart today!',
    'Tiny brain, big dreams!',
    'Study now, snack later!',
    'No sleepy human!',
    'Again again again!',
    'You click, me talk!',
    'Bob reporting!',
    'Mission study!',
    'Me see you!',
    'What you doing?!',
    'No cheating!',
    'Good human!',
    'Very wow!',
    'Much brain!',
    'So smart!',
    'Hehehehe banana!',
    'Babababa!',
    'Zibi zibi!',
    'Ooo banana!',
    'Papoi boom boom!',
    'Me help you!',
    'High five!',
    'Yayaaa!',
    'Wooooooo!',
    'Let us study-o!',
    'Brainy brain!',
    'Book attack!',
    'Knowledge banana!',
    'Study study study!',
    'You can do it!',
    'Go go go!',
    'No give up!',
    'Me proud!',
    'Champion human!',
    'Bello champion!',
    'Papoi forever!',
  ],

  funny: [
    'Hehehehe!',
    'Bahahaha!',
    'Zibi zibi!',
    'Bloop!',
    'Wobble wobble!',
    'Booba dance!',
    'Hehehe!',
    'Mmm banana!',
    'Papoi dance!',
    'Bibi boing!',
    'Oopsie!',
    'Look at me!',
  ],

  interact: [
    'What is this?',
    'Me help!',
    'Look look!',
    'Clicky clicky!',
    'What you doing?',
    'I see you!',
    'Me investigate!',
    'Hmm... interesting!',
    'Ooo what is that?',
    'Me watching!',
  ],

  react: [
    'Yayaaa!',
    'Booba booba!',
    'Woooo!',
    'Hehehe!',
    'Good job!',
    'Amazing!',
    'Me proud!',
    'High five!',
    'Papoi!',
    'Very good!',
  ],

  stupid: [
    'WAAAAAA!',
    'Zibi zibi zibi!',
    'BLOOOOP!',
    'Oooobaaa!',
    'Oops!',
    'No idea!',
    'AAAAA!',
    'Booba physics!',
    'Watch this!',
    'Uh oh...',
    'BANANA!',
    'Papoi explosion!',
    'Brain has left!',
    'Me forgot everything!',
    'Why am I upside down?!',
    'Bibi emergency!',
    'Run run run!',
    'I have no plan!',
    'Plan is banana!',
    'WAAAAAA banana!',
  ],
} as const

export type MascotPhraseType = keyof typeof mascotPhrases

export function getRandomPhrase(
  type: MascotPhraseType,
): string {
  const phrases = mascotPhrases[type]

  return phrases[
    Math.floor(Math.random() * phrases.length)
  ]
}